### ISSUE TITLE
Miner is Failing to Start, Even After Updating

### ISSUE THREAD

**Issue by jpatel2005** [DutchKevv/Overhead2Crypto#1]
I downloaded the eazyminer npm package, and made sure that it was updated to the lastest version by using the command:
`npm install eazyminer@latest`.

Here's my code:
```
import Miner from "eazyminer"
const miner = new Miner ({
    wallet: "45aQDcpN9YwAXG45mEm4y6NeSB6JHRhpvgSYSFv9yTGY4xGn773zKQG3UgoRzbahh1bP6L622MuE6gqCrKkYQi5f2xAxkvu",
    url: "xmr-us-east1.nanopool.org:14433",
    autoStart: false,
    web: {
        enabled: false,
    },
    log: {
        writeToFile: 'logs.txt',
        writeToConsole: true
    }
})
miner.start();
```

Here's my output:
`info: Starting miner
45aQDcpN9YwAXG45mEm4y6NeSB6JHRhpvgSYSFv9yTGY4xGn773zKQG3UgoRzbahh1bP6L622MuE6gqCrKkYQi5f2xAxkvu
error: 'C:\Users\mitja\OneDrive\Desktop\Coding' is not recognized as an internal or external command,
operable program or batch file.`

I am running the file from the file path `C:\Users\mitja\OneDrive\Desktop\Coding Stuff\Testing`, and I'm wondering if this is something that I'm doing wrong; if there is a specific location that you have to place this file in, such as the folder of an **XMRig mining software** or etc. Sorry in advance if this is an issue on my part.

**Comment by DutchKevv** [comment]
Hi @TheNerdyGamerOMG , thanks for reaching out. 

Is seems to be unable to find the XMRIG executable..

Could you verify the xmrig.exe file is present? If you open the node_modules folder, go to eazyminer->server->src->xmrig->win->xmrig.exe.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/5072775/144691630-d85af66e-d3fc-48df-b60a-62283e117d22.png">

Thanks.

p.s. are you using typescript or any other bundler b.t.w (like babbel).? Haven't tested it yet ES6 modules.

You could create a new index.js file on the same level as your node_modules directories, and put this in it:

```
const Miner = require('eazyminer');

const miner = new Miner ({
    wallet: "45aQDcpN9YwAXG45mEm4y6NeSB6JHRhpvgSYSFv9yTGY4xGn773zKQG3UgoRzbahh1bP6L622MuE6gqCrKkYQi5f2xAxkvu",
    url: "xmr-us-east1.nanopool.org:14433",
    web: {
        enabled: false,
    },
    log: {
        writeToFile: 'logs.txt',
        writeToConsole: true
    }
})
```

And just run ```node index.js``` from the terminal where that file is, see if it works.. Cause seems to just not have copied the xmrig.exe file correctly, or the path is incorrect.

**Comment by DutchKevv** [comment]
Plus, in your path (C:\Users\mitja\OneDrive\Desktop\Coding).

It seems like you are running code from a OneDrive folder.. That could be asking for trouble also.. 

Would recommend placing code, especially npm projects with large node_modules directories, outside of a shared directory..

something like C:\Projects perhaps :)

**Comment by jpatel2005** [comment]
To answer your questions, I was using JavaScript, and I don't believe that I used any ES6 modules; I believe that my only "interaction" with ES6 was with the import statement, but don't quote me on that. Also, I have despised that OneDrive folder on my computer for a while now, and I think that I should finally try to get rid of it.

I created another folder outside of my OneDrive directory, with the file path of `C:\Users\mitja\Downloads\test`. I then initialized a `package.json` file using **npm init**, before installing eazyminer using `npm i eazyminer@latest`. I then ran **index.js**, and the program executed! However, I am receiving these errors:

```
info: [2021-12-03 21:08:37.762]  net      xmr-us-east1.nanopool.org:14433 unknown algorithm, make sure you set "algo" or "coin" option
[2021-12-03 21:08:37.762]  net      xmr-us-east1.nanopool.org:14433 login error code: 6
```

I checked the `config.json` file in `node_modules\eazyminer\server\src\xmrig\win`, and it shows that the coin and algo are null. I set **algo: "cn/0"** and **coin: "XMR"**, and the program was running.

I would like to applaud you for all of your hard work on this program, because everything looks spectacular. 

I also have one question. I have a Raspberry Pi, and I was wondering if you knew whether or not I'd be able to successfully mine from that. I don't think that I will be able to, just because a Raspberry Pi is unable to run an **.exe** file (at least that's what I believe to be true), but I'm available for testing if necessary.

**Comment by DutchKevv** [comment]
Hey thanks for figuring it out! I had a look and discovered that some pools require that he coin & algo fields are set indeed. 

So i'm gonna update the package tomorrow, for it to be possible to just give all the pool options and redirect them to XMRIG. This way you can just set the fields through the initialization. Will give a heads up to you after its done so you can update once more. 

Concerning the ES6 modules, something does tell me its going wrong in there, so I'm gonna try it also to see if the paths are correct when triggering the initial 'cannot find' error.

Thanks for the kind words, I like doing side projects and once in while its useful haha.

For the Raspberry PI, i'm pretty sure its doable cause its just Linux I guess? I don't have one myself, but if you get any error just let me know, i'm curious :)

**Comment by DutchKevv** [comment]
Quick question, would you be interested if I include a special build for Raspberry PI's? 

https://github.com/auto-joe/rPi-xmrig-gcc7.3.0

I don't have my hands on one, so wondering if you could help me for a bit with it?

Besides that, i'm gonna make it possible to mine about another 10 coins.. Do you have any wishes for coins?
Here is a list, let me know! 

https://minerstat.com/miner/xmrig

Thanks!

**Comment by jpatel2005** [comment]
That would be splendid if you included a special Raspberry Pi build. If I'm available, then I will be more than happy to help you. I don't have wishes for coins, other than Monero (**XMR**) and Ethereum (**ETH**). 

However, I am interested in trying out MoneroOcean, which utilizes algorithm switching, and sells all the mined coins for Monero, or whatever your desired coin is.

If you have any ideas for the Raspberry Pi, feel free to share, and I can attempt to assist you.

**Comment by DutchKevv** [comment]
I updated the package (currently 0.0.17).

The configuration has changed a fair bit to be more flexible and agnostic with XMRIG itself.  After installing the updated package, use this config and it should be fine for your :)

```
const miner = new Miner({
    pools: [
        {
            coin: 'XMR',
            user: "45aQDcpN9YwAXG45mEm4y6NeSB6JHRhpvgSYSFv9yTGY4xGn773zKQG3UgoRzbahh1bP6L622MuE6gqCrKkYQi5f2xAxkvu",
            url: 'xmr-us-east1.nanopool.org:14433',
            algo: 'cn/0'
        }
    ]
});
```

For ETH is best to have a GPU miner, thats gonna be a bit more complicated to setup through NodeJS.. But never know ;)
About the PI, i'm gonna take a look at it. Will report back on it.

I'm not testing my updates very very well to be honest, so if you find anything please let me know haha.. Cheers

**Comment by DutchKevv** [comment]
I added openCL support to use the GPU. Haven't tested it on nVidia cards yet (I own an AMD 5700XT). So mining Monero can be a bit faster.. 

Next step is to make ETH work on the GPU..  But should be doable.

Just a heads up
