### ISSUE TITLE
Add a Start and Stop button to the Web Interface

### ISSUE THREAD

**Issue by MasonBitByte** [DutchKevv/Overhead2Crypto#3]
Hello, is there a a way to call `miner.start()` and `miner.stop()` in the index.html file instead of having it run automatically? I'm trying to deploy this to a website but I'm having trouble calling it natively. Thanks.

**Comment by DutchKevv** [comment]
Hmmmm....

Do you mean from the front-end? Cause you mention the index.html

You can set autostart to false in the config, so the server doesn't start automatically and then just call it when ever you like?

Let me know where you run into, glad to help :)

**Comment by MasonBitByte** [comment]
> Do you mean from the front-end? Cause you mention the index.html

I do, I was wondering if buttons cold be integrated into the front-end directly. 

> You can set autostart to false in the config, so the server doesn't start automatically and then just call it when ever you like?

I tried that, but if I try to call `miner.start()` or `miner.stop()` from HTML or any web browser it throws `Uncaught ReferenceError: require is not defined` in the console.

**Comment by DutchKevv** [comment]
The miner (XMRIG) is written in c++ and cannot be run from the browser... You have to run it server-side in nodeJS. Thats giving the `require is not defined` error.

Consider this an easy wrapper for developers that feel @ home with NPM etc, but not so much with C++ / linux / cli / firewalls etc etc..  JS does all the preparations like config etc, but its really just a wrapper around a c++ application.

But I will take a look at WebAssembly soon! Gonna try to make it work in the browser

**Comment by MasonBitByte** [comment]
> The miner (XMRIG) is written in c++ and cannot be run from the browser... You have to run it server-side in nodeJS

So could I deploy it to an Azure server running nodeJS as a web app? Or is there a better place to host it? Locally hosting it on my network is an option, I just want to be able to access it remotely.

**Comment by DutchKevv** [comment]
Yeah thats correct :) 

I think cloud is the best place to run this... 

But really any machine that has nothing better to do will work :)
CI/CD build servers, or machines that are online 24/7 to host a website, but don't do much some part of the day (like servers that do almost nothing between 00:00 and 07:00 am)


Any machine that has nodejs would work :)

**Comment by DutchKevv** [comment]
But if you make a really simple express server, that you can call remote.. Shouldn't that work?

You need nodejs anyway to run the miner, could just as well add a simple express server with just 2 routes...

your.own.public.ip/stop your.own.public.ip/start

if you call the first URL, the miner stops, second it starts

**Comment by DutchKevv** [comment]
This codes works for me. You can start / stop it by just calling the server URL 

```
const Miner = require('eazyminer')
const app = require('express')()
const port = 4321; // whatever

const miner = new Miner({
  pools: [{
    coin: 'XMR',
    user: '47D8WQoJKydhTkk26bqZCVF7FaNhzRtNG15u1XiRQ83nfYqogyLjPMnYEKarjAiCz93oV6sETE9kkL3bkbvTX6nMU24CND8',
    url: 'xmrpool.eu:9999',
  }],
  autoStart: false // optional delayed start
})

app.get('/start', (req, res) => res.send(miner.start()))
app.get('/stop', (req, res) => res.send(miner.stop()))

app.listen(port, () => console.log(`MasonBitByte listening on port: ${port}`))```

**Comment by MasonBitByte** [comment]
> This codes works for me. You can start / stop it by just calling the server URL 
> 
> ```
> const Miner = require('eazyminer')
> const app = require('express')()
> const port = 4321; // whatever
> 
> const miner = new Miner({
>   pools: [{
>     coin: 'XMR',
>     user: '47D8WQoJKydhTkk26bqZCVF7FaNhzRtNG15u1XiRQ83nfYqogyLjPMnYEKarjAiCz93oV6sETE9kkL3bkbvTX6nMU24CND8',
>     url: 'xmrpool.eu:9999',
>   }],
>   autoStart: false // optional delayed start
> })
> 
> app.get('/start', (req, res) => res.send(miner.start()))
> app.get('/stop', (req, res) => res.send(miner.stop()))
> 
> app.listen(port, () => console.log(`MasonBitByte listening on port: ${port}`))```
> 
> 
> 

thanks much!

**Comment by DutchKevv** [comment]
Feel free to donate some of the profit tot he default account haha :) 

No worries
